name: Lint and Test

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: echo "Building branch $GITHUB_REF"
      - run: npm ci
        env:
          GH_PKG_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run build --if-present
      - run: npm run format
      - run: npm run lint
      - run: npm test
